### PR TITLE
Copy calculation result to clipboard

### PR DESCRIPTION
**Pull request by ito32bit**
Screenshot:
lxqt-runner_calc2

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
GTM and a good idea.

**Comment by stefonarch** [comment]
Cool! Could you run `lxqt-transupdate` in the branch and force-push the commit so change will go to weblate immediately?

**Comment by tsujan** [comment]
@stefonarch 
It's better NOT to do that in code PRs. It would complicate the review process.

**Comment by stefonarch** [comment]
Ok, will do it after merging. Tested and working.

**Pull request merged**
