### PR TITLE
Lower "top" position

### PR DESCRIPTION
**Pull request by stefonarch**
The actual top position is not very user friendly IMO, as there may be already panels, title bars and so on.

Related https://github.com/lxqt/lxqt-runner/issues/244

### CODE REVIEW

**Comment by tsujan** [comment]
Since Runner hides as soon as the user focuses/activates another window, I see no problem with the top position. Any other position may feel weird in practice.

**Comment by stefonarch** [comment]
I remember using krunner ages ago it had a setting "custom position" -  you could drag it wherever you liked. With kwin_x11 I use a window rule for the position which for me is most natural (more or less the one of this PR):

screen_full_mar_20:59:44_

**Comment by tsujan** [comment]
I have no problem with a gap but, IMO, it needs to be optional, i.e., in the config dialog.

However, there's another possibility: to make Runner remember its position. Its position can be changed with most WMs (usually by using Alt+Drag). Remembering the new position should be optional too. That will also cover the KDE case you mentioned.

Yet another possibility is remembering the position only for the current session, or making that optional too.

Since I think we don't want too many options, we have to decide which direction to go in.

**Comment by stefonarch** [comment]
Just add "custom position" to the both existing could cover all. Personally I can't see a need for  "Only for current session" though.

**Comment by tsujan** [comment]
What you said here and in https://github.com/lxqt/lxqt-runner/issues/244 point to different directions:

 1. Just add a custom gap at the top.
 2. Add left, right and bottom plus a gap for each.
 3. Add  left, right, bottom and center (of course without a gap — a gap doesn't make sense for the center).
 4. Forget about left, right,..., center and gap; just make it remember its position.

These choices are incompatible with each other, e.g., if we do 1 and later decide to do 4, the code of 1 will be removed. That's why I said we have to make a decision.

Personally, I don't like 4; a floating Runner isn't good, IMO.

**Comment by stefonarch** [comment]
I don't like 4. too, IMO is should be  centered horizontally always but allow different heights?
This could be achieved with just one option: a gap +/- from center, or by "center,top,custom gap" or by adding custom position but only vertically which is maybe more user friendly than trying out gap numbers.

**Comment by tsujan** [comment]
> or by adding custom position but only vertically

That's nothing but a top gap.

I like 3 minus left and right. It's clean and simple to the user: top, bottom and center. The left and right sides aren't good for a horizontal text entry.

**Comment by tsujan** [comment]
Wait a minute! I'd forgotten that the center was already covered :P The option for the gap can be like "Top margin: SPIN-BOX"  — a gap from the center doesn't make much sense, especially with this. The option should be disabled when the user chooses the center.

And, really, do we need an option for the bottom?

**Comment by stefonarch** [comment]
I tried a gap from top but it complained so I used one from center.
Bottom would be strange I agree, but it could be achieved then with a big gap top value if somebody insists :)

So yes, adding "Top margin: SPIN-BOX"  and stop to the existing is ok for me.

**Comment by stefonarch** [comment]
Done in https://github.com/lxqt/lxqt-runner/pull/255/commits/83763971dffcea18af3d9864858558b2b4657686

**Pull request closed without merging**
