### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/lxqt-desktop/lxqt-runner/) for LXQt Desktop/lxqt-runner.

### CODE REVIEW

**Comment by tsujan** [comment]
This needs to be done for other projects too.

**Comment by stefonarch** [comment]
Wanted to test it here. I wonder if we should add some more text, or an explicit link - maybe someone doesn't see that the widget is a link.

**Comment by tsujan** [comment]
> I wonder if we should add some more text, or an explicit link

I think "Translation (Weblate)" is enough; the link can be added to it.

**Comment by stefonarch** [comment]
> I think "Translation (Weblate)" is enoug; the link can be added to it.

It's a title, don't like it to be link. Added this   in lximage-qt:

> ### Translation

> Translations can be done in [LXQt-weblate](https://translate.lxqt-project.org/projects/lxqt-desktop/lximage-qt/)
>  think "Translation (Weblate)" is enoug
> <a href="https://translate.lxqt-project.org/projects/lxqt-desktop/lximage-qt/">
> <img src="https://translate.lxqt-project.org/widgets/lxqt-desktop/-/lximage-qt/multi-auto.svg" alt="Stato traduz>"
> </a>

Btw found this comment just per case, because it's the Bot who did the push.

**Comment by tsujan** [comment]
> Added this in lximage-qt:

I think it's perfect.

> Btw found your comment just per case, because it's the Bot who did the push.

Oh, I didn't know that. Thanks for telling me!

**Comment by stefonarch** [comment]
> I think it's perfect.

ok, than I go for the others in the same way, did an template in featherpad with search and replace, lots of repos...

**Comment by stefonarch** [comment]
> Oh, I didn't know that. Thanks for telling me!

I think @yan12125 gets notified about comments in the bot.

**Comment by palinek** [comment]
Just one nitpicker question.... can order of languages in the widget be configured in weblate? From the picture above it seems like random...

**Comment by stefonarch** [comment]
I don't see any option, a widget can be project-wide (lxqt-desktop) or component-specific. 
But yes, I cannot see any logic in it. 
Here it looks better: https://github.com/lxqt/lxqt-runner#translation-weblate

**Pull request merged**
