### PR TITLE
Added scope=launcher

### PR DESCRIPTION
**Pull request by stefonarch**
We have set scope in all (`lxqt-leave` has "window" afaik) layershell applications:
```
$ hyprctl layers
Monitor eDP-1:
        Layer level 0 (background):
                Layer 649ee26d0d20: xywh: 0 0 1920 1080, namespace: desktop
        Layer level 1 (bottom):
        Layer level 2 (top):
                Layer 649ee264de10: xywh: 0 0 1920 48, namespace: dock
                Layer 649ee14f4600: xywh: 1877 235 43 658, namespace: dock
                Layer 649ee23d0f20: xywh: 161 1037 1555 43, namespace: dock
                Layer 649ee125faf0: xywh: 688.5 267 500 46, namespace: launcher
        Layer level 3 (overlay):
                Layer 649ee2876ff0: xywh: 1341 50 534 89, namespace: notification

```
It makes it possible to add layer rules in compositor which support them, for example 
```
layerrule = noanim, launcher
layerrule = dimaround, launcher
```

### CODE REVIEW

**Comment by tsujan** [comment]
Although it's just a name to be found, I think `runner` is better.

**Comment by stefonarch** [comment]
I've no idea if there is some standard, like using "dock" for panel, so "launcher" seems to be more general to me.

**Comment by tsujan** [comment]
By using a scope, you mark it to find it later — in fact, you let the user find it. Since it's `lxqt-runner`, a fast guess would be "runner".

I know you need that scope with compositors that have problems; just wanted to make life easier for their users ;)

**Comment by stefonarch** [comment]
>I know you need that scope with compositors that have problems

No problem, it's only a matter of taste if runner has animations or not :)

https://github.com/user-attachments/assets/98206238-7040-409e-b721-c9d83eb49514

**Comment by stefonarch** [comment]
I checked [fuzzel](https://codeberg.org/dnkl/fuzzel/src/commit/3b6966d48eee1fa0408e8187fa78b87b7418e42e/wayland.c#L2436), it uses "launcher" as well. Any objections to merge this?

**Review by tsujan — APPROVED** [review]
It had no problem. I just prefer "runner" because other kinds of apps may introduce themselves as "launcher" too — you mentioned `fuzzel`.

GTM.

**Comment by stefonarch** [comment]
> other kinds of apps may introduce themselves as "launcher" too

My understanding is that "scope" is kind of the typeof the app: both waybar and lxqt-panel will be seen as "docks".

**Pull request merged**
