### PR TITLE
Added an option for top margin

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Review by stefonarch — COMMENTED** [review]
There is an issue, it looks like changed settings are only applied after restart lxqt-runner module or relogin. Tested with openbox, kwin and xfwm4, at some point in openbox it opened at 100 100 with 100px margin. Will look again in openbox.

**Comment by stefonarch** [comment]
Looked again in openbox, it's weird:

1. change settings or margin, not applied
2. restart runner module
3. it opens with any margin at ~ 170 130 and sometimes while using it it will start at the correct position.

**Comment by stefonarch** [comment]
It looks like all those issues are in my home dir, but no idea where. 
Testing with a clean user everything works as expected, with any WM.

**Comment by tsujan** [comment]
I can't see any issue here. Since you go back and forth between X11 and Wayland, I suspect an interference caused by that (patches, double config files,...).

**Comment by tsujan** [comment]
Another possibility is that you didn't stop the process of `lxqt-runner` before each test.

The patch is too simple to cause a complex behavior.

**Review by stefonarch — APPROVED** [review]

**Pull request merged**
